### ISSUE TITLE
Update badge hiding to use visibility instead of display

### ISSUE THREAD

**Issue by aentwist** [AurityLab/recaptcha-v3#318]
The [reCAPTCHA docs FAQ](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) specifies how to hide the reCAPTCHA badge.
> Note: if you choose to hide the badge, please use
```css
.grecaptcha-badge { visibility: hidden; }
```

I noticed that when using the option `autoHideBadge: true`, `display: none` is used instead.
```css
.grecaptcha-badge {
  display: none !important;
}
```

If there was not a specific reason for this, then the rule should be updated to use `visibility: hidden`.
